<a href="https://colab.research.google.com/github/melissagaleanot-crypto/entregable-pandas-numpy/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

dataframe_url = 'https://www.datos.gov.co/resource/sfcd-b3ey.json'
df = pd.read_json(dataframe_url)
df.head()

,tipodeinformacion,tipodetarifa,tipodedato,rangodeconsumo,nivel,propiedadepm,compartido,propiedaddelcliente,punta,fueradepunta,year,mes
0,Monomia,Áreas Comunes,Con Contribución,N/A,I,684.23,656.43,628.62,0.0,0.0,2020.0,Diciembre
1,Monomia,Áreas Comunes,Sin Contribución,N/A,I,570.20,547.02,523.85,0.0,0.0,2020.0,Diciembre
2,Monomia,Áreas Comunes,Con Contribución,N/A,I,695.93,667.65,639.36,0.0,0.0,2021.0,Marzo
3,Monomia,Áreas Comunes,Sin Contribución,N/A,I,579.94,556.37,532.80,0.0,0.0,2021.0,Marzo
4,Monomia,Áreas Comunes,Con Contribución,N/A,I,680.83,653.16,625.49,0.0,0.0,2020.0,Mayo

In [ ]:
#explorar datos...

df.tail() # obtiene los datos de la cola del df

,tipodeinformacion,tipodetarifa,tipodedato,rangodeconsumo,nivel,propiedadepm,compartido,propiedaddelcliente,punta,fueradepunta,year,mes
995,Horaria,Costo Unitario,Restricciones: Rm,N/A,III,0.00,0.00,0.00,24.10,26.29,2017.0,Mayo
996,Horaria,Costo Unitario,"Costo G,T, pérdidas: PRn,m",N/A,IV,0.00,0.00,0.00,4.72,4.47,2017.0,Noviembre
997,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.00,0.00,2016.0,Diciembre
998,Horaria,Costo Unitario,"Costo G,T, pérdidas: PRn,m",Fuera de Punta,I,31.71,31.71,31.71,0.00,0.00,2017.0,Octubre
999,Horaria,Costo Unitario,"Costo compra: Gm, i",N/A,II,0.00,0.00,0.00,162.89,159.98,2017.0,Mayo

In [ ]:
# eliminando propiedades de EPM con valor = a 0.00

df = df[df['propiedadepm'] != 0]
df.tail() #Si comparamos el primer tail() las propiedadesepm no contienen valores equivalentes a cero

,tipodeinformacion,tipodetarifa,tipodedato,rangodeconsumo,nivel,propiedadepm,compartido,propiedaddelcliente,punta,fueradepunta,year,mes
992,Monomia,Costo Unitario,Cargo transporte STN: Tm,N/A,I,21.26,21.26,21.26,0.0,0.0,2017.0,Junio
993,Horaria,Costo Unitario,"Costo compra: Gm, i",Fuera de Punta,I,148.94,148.94,148.94,0.0,0.0,2017.0,Enero
994,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,177.09,159.67,142.26,0.0,0.0,2016.0,Diciembre
997,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.0,0.0,2016.0,Diciembre
998,Horaria,Costo Unitario,"Costo G,T, pérdidas: PRn,m",Fuera de Punta,I,31.71,31.71,31.71,0.0,0.0,2017.0,Octubre

In [ ]:
# Obtener datos por columnas especificas (Filtrado)

df_colums_unique = df[['tipodeinformacion','rangodeconsumo', 'propiedaddelcliente']]
df_colums_unique_filter = df_colums_unique[df_colums_unique['rangodeconsumo'] != "N/A"]
df_colums_unique_filter.head()

    tipodeinformacion rangodeconsumo  propiedaddelcliente
128           Horaria          Punta               219.34
129           Horaria          Punta                34.22
130           Horaria          Punta               166.25
131           Horaria          Punta                50.32
132           Horaria          Punta                49.44

In [ ]:
# Obtener de df_colums_unique_filter la suma de las propiedades de cliente superiores a 150 y menores a 160 con tipo de consumo punta y tipo de informacion horaria

df_colums_unique_filter.query('propiedaddelcliente > 150 and propiedaddelcliente < 160 and rangodeconsumo == "Punta" and tipodeinformacion == "Horaria"')

    tipodeinformacion rangodeconsumo  propiedaddelcliente
536           Horaria          Punta               154.63
621           Horaria          Punta               159.53
688           Horaria          Punta               158.56
928           Horaria          Punta               151.88

In [ ]:
#Organizar valores del DF inicial en orden decendente y posteriormente retirar los que no se encuentran en el rando de propiedaddelcliente determinado

df_sorted = df.sort_values(by=['propiedaddelcliente'], ascending=False)
df_sorted.query("propiedaddelcliente > 100 and propiedaddelcliente < 140")

,tipodeinformacion,tipodetarifa,tipodedato,rangodeconsumo,nivel,propiedadepm,compartido,propiedaddelcliente,punta,fueradepunta,year,mes
951,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,174.69,157.32,139.95,0.0,0.0,2017.0,Marzo
815,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Fuera de Punta,I,174.69,157.32,139.95,0.0,0.0,2017.0,Marzo
546,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Fuera de Punta,I,174.29,156.85,139.40,0.0,0.0,2017.0,Septiembre
539,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,174.29,156.85,139.40,0.0,0.0,2017.0,Septiembre
818,Monomia,Costo Unitario,"Cargo transporte SDL: Dn,m",N/A,I,174.29,156.85,139.40,0.0,0.0,2017.0,Septiembre
745,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,173.42,156.08,138.74,0.0,0.0,2017.0,Junio
923,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,173.17,155.84,138.50,0.0,0.0,2017.0,Mayo
848,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Fuera de Punta,I,173.01,155.66,138.32,0.0,0.0,2017.0,Enero
845,Monomia,Costo Unitario,"Cargo transporte SDL: Dn,m",N/A,I,173.01,155.66,138.32,0.0,0.0,2017.0,Enero
883,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,173.55,155.88,138.22,0.0,0.0,2018.0,Enero
819,Horaria,Costo Unitario,"Cargo transporte SDL: Dn,m",Punta,I,172.65,155.25,137.84,0.0,0.0,2017.0,Febrero
774,Monomia,Costo Unitario,"Cargo transporte SDL: Dn,m",N/A,I,172.65,155.25,137.84,0.0,0.0,2017.0,Febrero

In [34]:
#df punta diferente de 0

df_shared = df[df['compartido'] > 150 ]
df_rango = df[df['rangodeconsumo'] == 'Punta']
df_rango.merge(df_shared, on='tipodeinformacion')

,tipodeinformacion,tipodetarifa_x,tipodedato_x,rangodeconsumo_x,nivel_x,propiedadepm_x,compartido_x,propiedaddelcliente_x,punta_x,fueradepunta_x,...,tipodedato_y,rangodeconsumo_y,nivel_y,propiedadepm_y,compartido_y,propiedaddelcliente_y,punta_y,fueradepunta_y,year_y,mes_y
0,Horaria,Costo Unitario,"Costo compra: Gm,i",Punta,I,219.34,219.34,219.34,0.0,0.0,...,"Costo compra: Gm,i",Punta,I,219.34,219.34,219.34,0.0,0.0,2020.0,Diciembre
1,Horaria,Costo Unitario,"Costo compra: Gm,i",Punta,I,219.34,219.34,219.34,0.0,0.0,...,"Cargo transporte SDL: Dn,m",Punta,I,211.37,188.81,166.25,0.0,0.0,2020.0,Diciembre
2,Horaria,Costo Unitario,"Costo compra: Gm,i",Punta,I,219.34,219.34,219.34,0.0,0.0,...,"Costo compra: Gm,i",Fuera de Punta,I,215.25,215.25,215.25,0.0,0.0,2020.0,Diciembre
3,Horaria,Costo Unitario,"Costo compra: Gm,i",Punta,I,219.34,219.34,219.34,0.0,0.0,...,"Cargo transporte SDL: Dn,m",Fuera de Punta,I,211.37,188.81,166.25,0.0,0.0,2020.0,Diciembre
4,Horaria,Costo Unitario,"Costo compra: Gm,i",Punta,I,219.34,219.34,219.34,0.0,0.0,...,"Costo compra: Gm,i",Punta,I,216.84,216.84,216.84,0.0,0.0,2020.0,Mayo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37837,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.0,0.0,...,"Cargo transporte SDL: Dn,m",Punta,I,174.69,157.32,139.95,0.0,0.0,2017.0,Marzo
37838,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.0,0.0,...,"Cargo transporte SDL: Dn,m",Fuera de Punta,I,175.99,158.57,141.14,0.0,0.0,2017.0,Octubre
37839,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.0,0.0,...,"Costo compra: Gm, i",Fuera de Punta,I,157.97,157.97,157.97,0.0,0.0,2017.0,Junio
37840,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.0,0.0,...,"Costo compra: Gm, i",Fuera de Punta,I,176.61,176.61,176.61,0.0,0.0,2018.0,Abril
37841,Horaria,Costo Unitario,Cargo transporte STN: Tm,Punta,I,34.62,34.62,34.62,0.0,0.0,...,"Cargo transporte SDL: Dn,m",Punta,I,177.09,159.67,142.26,0.0,0.0,2016.0,Diciembre